name: github activity feed

inputs:
  GH_USERNAME:
    default: ${{ github.repository_owner }}
    required: false
  CONFIG_FILE:
    default: "./.github/github_activity.config.yml"
    required: true

branding:
  color: orange
  icon: activity

runs:
  using: node12
  main: dist/index.js
  
